version: "3"

services:
  app:
    image: app:build
    env_file: .env
    stdin_open: true
    tty: true
    links:
      - db
      - smtp
      - redis
    volumes:
      - ./app:/app
      - static_volume:/app/experimenter/served/
    command: bash -c "/app/bin/wait-for-it.sh db:5432 -- python /app/manage.py collectstatic --noinput; python /app/manage.py runserver 0:7001"
    networks:
      - private_nw

  worker:
    image: app:build
    env_file: .env
    links:
      - db
      - smtp
      - redis
    volumes:
      - ./app:/app
    command: bash -c "/app/bin/wait-for-it.sh db:5432 -- celery -A experimenter worker -l debug"
    networks:
      - private_nw
      - public_nw

  nginx:
    build: ./nginx
    env_file: .env
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - private_nw
      - public_nw
    volumes:
      - static_volume:/app/experimenter/served/

  db:
    restart: always
    image: postgres:9.6
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - private_nw

  redis:
    image: redis
    networks:
      - private_nw

  smtp:
    image: python:3.6
    ports:
      - "25:25"
    networks:
      - private_nw
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m smtpd -n -c DebuggingServer 0.0.0.0:25

volumes:
  db_volume:
  static_volume:

networks:
  private_nw:
    internal: true
  public_nw:
